"""add name column to t_users

Revision ID: 6705fabde47b
Revises: 9d83d9da221a
Create Date: 2025-05-04 10:01:45.719966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6705fabde47b'
down_revision: Union[str, None] = '9d83d9da221a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('t_users', sa.Column('provider_id', sa.String(length=100), nullable=False))
    op.add_column('t_users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('t_users', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('t_users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('t_users', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('t_users', 'is_active')
    op.drop_column('t_users', 'provider_id')
    op.drop_column('t_users', 'name')
    # ### end Alembic commands ###
