"""create t_users

Revision ID: 9d83d9da221a
Revises: 
Create Date: 2025-05-04 09:37:12.723920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d83d9da221a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_t_users_id'), 't_users', ['id'], unique=False)
    op.alter_column('t_choices', 'choice_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('t_choices', 'choice_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('t_choices_question_id_fkey', 't_choices', type_='foreignkey')
    op.create_foreign_key(None, 't_choices', 't_questions', ['question_id'], ['id'])
    op.create_index(op.f('ix_t_exam_rounds_id'), 't_exam_rounds', ['id'], unique=False)
    op.drop_constraint('t_exam_rounds_exam_id_fkey', 't_exam_rounds', type_='foreignkey')
    op.create_foreign_key(None, 't_exam_rounds', 't_exams', ['exam_id'], ['id'])
    op.drop_constraint('t_exams_exam_code_key', 't_exams', type_='unique')
    op.create_index(op.f('ix_t_exams_exam_code'), 't_exams', ['exam_code'], unique=True)
    op.create_index(op.f('ix_t_exams_id'), 't_exams', ['id'], unique=False)
    op.alter_column('t_questions', 'question_answer',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.create_foreign_key(None, 't_questions', 't_round_subjects', ['round_subject_id'], ['id'])
    op.create_index(op.f('ix_t_subjects_id'), 't_subjects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_subjects_id'), table_name='t_subjects')
    op.drop_constraint(None, 't_questions', type_='foreignkey')
    op.alter_column('t_questions', 'question_answer',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_t_exams_id'), table_name='t_exams')
    op.drop_index(op.f('ix_t_exams_exam_code'), table_name='t_exams')
    op.create_unique_constraint('t_exams_exam_code_key', 't_exams', ['exam_code'])
    op.drop_constraint(None, 't_exam_rounds', type_='foreignkey')
    op.create_foreign_key('t_exam_rounds_exam_id_fkey', 't_exam_rounds', 't_exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_t_exam_rounds_id'), table_name='t_exam_rounds')
    op.drop_constraint(None, 't_choices', type_='foreignkey')
    op.create_foreign_key('t_choices_question_id_fkey', 't_choices', 't_questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.alter_column('t_choices', 'choice_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('t_choices', 'choice_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_t_users_id'), table_name='t_users')
    op.drop_table('t_users')
    # ### end Alembic commands ###
